name: NuxieSDK
options:
  bundleIdPrefix: com.nuxie
  deploymentTarget:
    iOS: 15.0
  generateEmptyDirectories: true
  groupSortPosition: top
  
packages:
  Quick:
    url: https://github.com/Quick/Quick.git
    from: 7.0.0
  Nimble:
    url: https://github.com/Quick/Nimble.git
    from: 13.0.0
  Factory:
    url: https://github.com/hmlongco/Factory.git
    from: 2.5.0
    
targets:
  NuxieSDK:
    type: framework
    platform: iOS
    sources:
      - path: Sources/Nuxie
        name: Nuxie
        excludes:
          - "**/*.md"
    dependencies:
      - package: Factory
        product: FactoryKit
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.nuxie.sdk
      PRODUCT_NAME: Nuxie
      MARKETING_VERSION: 0.1.0
      CURRENT_PROJECT_VERSION: 1
      SWIFT_VERSION: 5.9
      ENABLE_TESTABILITY: YES
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: ""
      
  NuxieSDKUnitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/NuxieUnitTests
        name: NuxieUnitTests
      - path: Tests/NuxieTestSupport
        name: NuxieTestSupport
    dependencies:
      - target: NuxieSDK
      - package: Quick
      - package: Nimble
      - package: Factory
        product: FactoryKit
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.nuxie.sdk.unittests
      TEST_HOST: ""
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: ""
    scheme:
      testTargets:
        - NuxieSDKUnitTests
      gatherCoverageData: true

  NuxieSDKIntegrationTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/NuxieIntegrationTests
        name: NuxieIntegrationTests
      - path: Tests/NuxieTestSupport
        name: NuxieTestSupport
    dependencies:
      - target: NuxieSDK
      - package: Quick
      - package: Nimble
      - package: Factory
        product: FactoryKit
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.nuxie.sdk.integrationtests
      TEST_HOST: ""
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: ""
    scheme:
      testTargets:
        - NuxieSDKIntegrationTests
      gatherCoverageData: false

  NuxieSDKE2ETests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/NuxieE2ETests
        name: NuxieE2ETests
      - path: Tests/NuxieTestSupport
        name: NuxieTestSupport
    dependencies:
      - target: NuxieSDK
      - package: Quick
      - package: Nimble
      - package: Factory
        product: FactoryKit
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.nuxie.sdk.e2etests
      TEST_HOST: ""
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: ""
    scheme:
      testTargets:
        - NuxieSDKE2ETests
      gatherCoverageData: false
      
schemes:
  NuxieSDK:
    build:
      targets:
        NuxieSDK: all
    test:
      targets:
        - NuxieSDKUnitTests
      gatherCoverageData: true
    run:
      config: Debug
    archive:
      config: Release

  NuxieSDKUnitTests:
    build:
      targets:
        NuxieSDK: all
    test:
      targets:
        - NuxieSDKUnitTests
      gatherCoverageData: true

  NuxieSDKIntegrationTests:
    build:
      targets:
        NuxieSDK: all
    test:
      targets:
        - NuxieSDKIntegrationTests
      gatherCoverageData: false

  NuxieSDKE2ETests:
    build:
      targets:
        NuxieSDK: all
    test:
      targets:
        - NuxieSDKE2ETests
      gatherCoverageData: false
