name: NuxieRevenueCatExample
options:
  bundleIdPrefix: io.nuxie.example

packages:
  Nuxie:
    path: ../../
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios.git
    branch: main

targets:
  RevenueCatExample:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - Sources
    dependencies:
      - package: Nuxie
        product: Nuxie
      - package: Nuxie
        product: NuxieRevenueCat
      - package: RevenueCat
        product: RevenueCat
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: io.nuxie.example.revenuecat
      PRODUCT_NAME: Nuxie + RevenueCat
      INFOPLIST_FILE: Sources/Info.plist
      SWIFT_VERSION: "5.9"
      TARGETED_DEVICE_FAMILY: "1,2"

schemes:
  RevenueCatExample:
    build:
      targets:
        RevenueCatExample: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
