name: MoodLog-RevenueCat
options:
  bundleIdPrefix: io.nuxie
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: en
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  defaultConfig: Debug

settings:
  base:
    PRODUCT_NAME: MoodLog (RevenueCat)
    PRODUCT_BUNDLE_IDENTIFIER: io.nuxie.examples.moodlog.swiftui.revenuecat
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    INFOPLIST_FILE: Sources/App/Info.plist
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    TARGETED_DEVICE_FAMILY: "1" # iPhone only
    SUPPORTS_MACCATALYST: false
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
    ENABLE_PREVIEWS: true

targets:
  MoodLog-RevenueCat:
    type: application
    platform: iOS

    sources:
      - path: Sources

    dependencies:
      - package: Nuxie
        product: Nuxie
      - package: Nuxie
        product: NuxieRevenueCat

    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""

packages:
  Nuxie:
    path: ../../
