name: NuxieE2EApp
options:
  bundleIdPrefix: io.nuxie
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: en
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  defaultConfig: Debug

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    TARGETED_DEVICE_FAMILY: "1"
    SUPPORTS_MACCATALYST: false
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
    ENABLE_PREVIEWS: true

targets:
  NuxieE2EApp:
    type: application
    platform: iOS

    sources:
      - path: Sources

    dependencies:
      - package: Nuxie

    settings:
      base:
        PRODUCT_NAME: NuxieE2EApp
        PRODUCT_BUNDLE_IDENTIFIER: io.nuxie.e2eapp
        INFOPLIST_FILE: Sources/App/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""

  NuxieE2EAppTests:
    type: bundle.unit-test
    platform: iOS

    sources:
      - path: Tests/Unit

    dependencies:
      - target: NuxieE2EApp
      - package: Nuxie

    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: io.nuxie.e2eapp.tests

  NuxieE2EAppUITests:
    type: bundle.ui-testing
    platform: iOS

    sources:
      - path: Tests/UI

    dependencies:
      - target: NuxieE2EApp

    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: io.nuxie.e2eapp.uitests

packages:
  Nuxie:
    path: ../../

schemes:
  NuxieE2EApp:
    build:
      targets:
        NuxieE2EApp: all
    test:
      targets:
        - NuxieE2EAppTests
        - NuxieE2EAppUITests
      config: Debug
    run:
      config: Debug
